url: https://zoeleblanc.github.io/
baseurl: /portfolio/

# Site settings
title: Zoe's Portfolio
email: zgleblanc@gmail.com
description: "Some posters and web design"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/Zoe_LeBlanc
  - title: github
    url: http://github.com/zoeleblanc

# Build settings
markdown: kramdown
permalink: pretty