
url: https://zoeleblanc.com/old_site/portfolio

# Site settings
title: Zoe's Portfolio
email: zgleblanc@gmail.com

description: "All my current projects. Sort them by category"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 726e7b
  secondary: 333  
  secondary-dark: 000

# Build settings
markdown: kramdown
permalink: pretty